# k8s/secrets/airflow-env-vars.yaml
apiVersion: v1
kind: Secret
metadata:
  name: airflow-env-vars
  namespace: airflow
type: Opaque
data:
  YOUTH_HOUSING_SENDER_EMAIL: ${YOUTH_HOUSING_SENDER_EMAIL_BASE64}
  YOUTH_HOUSING_SENDER_PASSWORD: ${YOUTH_HOUSING_SENDER_PASSWORD_BASE64}
  YOUTH_HOUSING_RECEIVER_EMAILS: ${YOUTH_HOUSING_RECEIVER_EMAILS_BASE64}