executor: "KubernetesExecutor"

config:
  core:
    dags_folder: "/opt/airflow/dags/repo/dags"
    executor: "KubernetesExecutor"
    dags_are_paused_at_creation: "True"
    load_examples: "False"
  api:
    auth_backend: "airflow.api.auth.backend.basic_auth"
  logging:
    remote_logging: "False"
    logging_level: "INFO"
  kubernetes:
    delete_worker_pods: "False"
    delete_worker_pods_on_failure: "False"
    delete_worker_pods_on_success: "False"

images:
  airflow:
    repository: "dave126/airflow-custom"
    tag: "2.9.3-amd64"
    pullPolicy: "Always"

airflow:
  # 1) 기존 시크릿 환경변수 불러오기
  extraEnvFrom:
    - secretRef:
        name: airflow-env-vars

  extraEnv:
    # 2) Postgres 연결
    - name: AIRFLOW_CONN_POSTGRES_DEFAULT
      valueFrom:
        secretKeyRef:
          name: airflow-postgresql
          key: postgres-password

    # 3) 이메일 발송용 시크릿 변수
    - name: YOUTH_HOUSING_SENDER_EMAIL
      valueFrom:
        secretKeyRef:
          name: airflow-env-vars
          key: YOUTH_HOUSING_SENDER_EMAIL
    - name: YOUTH_HOUSING_SENDER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: airflow-env-vars
          key: YOUTH_HOUSING_SENDER_PASSWORD
    - name: YOUTH_HOUSING_RECEIVER_EMAILS
      valueFrom:
        secretKeyRef:
          name: airflow-env-vars
          key: YOUTH_HOUSING_RECEIVER_EMAILS

    # 4) SMTP 설정 (airflow.cfg [email] 섹션 오버라이드)
    - name: AIRFLOW__EMAIL__SMTP_HOST
      value: "smtp.gmail.com"
    - name: AIRFLOW__EMAIL__SMTP_PORT
      value: "465"
    - name: AIRFLOW__EMAIL__SMTP_STARTTLS
      value: "False"
    - name: AIRFLOW__EMAIL__SMTP_SSL
      value: "True"
    - name: AIRFLOW__EMAIL__SMTP_USER
      valueFrom:
        secretKeyRef:
          name: airflow-env-vars
          key: YOUTH_HOUSING_SENDER_EMAIL
    - name: AIRFLOW__EMAIL__SMTP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: airflow-env-vars
          key: YOUTH_HOUSING_SENDER_PASSWORD
    - name: AIRFLOW__EMAIL__SMTP_MAIL_FROM
      valueFrom:
        secretKeyRef:
          name: airflow-env-vars
          key: YOUTH_HOUSING_SENDER_EMAIL

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/Seungyeup/ScrapeAndAlert.git"
    ref: "main"
    branch: "main"
    subPath: "dags"
    wait: 60
    # credentialsSecret: "git-credentials"  # public repo 전환으로 비활성화

webserver:
  service:
    type: "NodePort"
    ports:
      - name: "airflow-ui"
        port: 8080
        targetPort: "airflow-ui"
        nodePort: 30097

postgresql:
  primary:
    persistence:
      enabled: true
      storageClass: "local-path"