executor: "KubernetesExecutor"

images:
  airflow:
    repository: "dave126/airflow-custom"
    tag: "2.9.3-amd64"
    pullPolicy: "Always"

airflow:
  config:
    AIRFLOW__CORE__EXECUTOR: "KubernetesExecutor"
    AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags/repo/dags"
    AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
    AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.basic_auth"
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE: "False"
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_SUCCESS: "False"


  extraEnv:
    - name: YOUTH_HOUSING_SENDER_EMAIL
      valueFrom:
        secretKeyRef:
          name: "airflow-env-vars"
          key: "YOUTH_HOUSING_SENDER_EMAIL"
    - name: YOUTH_HOUSING_SENDER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "airflow-env-vars"
          key: "YOUTH_HOUSING_SENDER_PASSWORD"
    - name: YOUTH_HOUSING_RECEIVER_EMAILS
      valueFrom:
        secretKeyRef:
          name: "airflow-env-vars"
          key: "YOUTH_HOUSING_RECEIVER_EMAILS"

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/Seungyeup/ScrapeAndAlert.git"
    ref: "main"
    branch: "main"
    subPath: "dags"
    wait: 60
    # credentialsSecret: "git-credentials" # public repo로 전환되어 비활성화

webserver:
  service:
    type: "NodePort"
    ports:
      - name: "airflow-ui"
        port: 8080
        targetPort: "airflow-ui"
        nodePort: 30097


postgresql:
  primary:
    persistence:
      enabled: true
      storageClass: "local-path"