executor: "KubernetesExecutor"

config:
  core:
    dags_folder: "/opt/airflow/dags/repo/dags"
    executor: "KubernetesExecutor"
    dags_are_paused_at_creation: "True"
    load_examples: "False"
  api:
    auth_backend: "airflow.api.auth.backend.basic_auth"
  logging:
    remote_logging: "False"
    logging_level: "INFO"
  kubernetes:
    delete_worker_pods: "False"
    delete_worker_pods_on_failure: "False"
    delete_worker_pods_on_success: "False"

images:
  airflow:
    repository: "dave126/airflow-custom"
    tag: "2.9.3-amd64"
    pullPolicy: "Always"

airflow:
  extraEnv:
    - name: AIRFLOW_CONN_POSTGRES_DEFAULT
      valueFrom:
        secretKeyRef:
          name: airflow-postgresql       # PostgreSQL Secret 이름
          key:  postgres-password        # Secret에 저장된 비밀번호 키
    - name: YOUTH_HOUSING_SENDER_EMAIL
      valueFrom:
        secretKeyRef:
          name: "airflow-env-vars"
          key: "YOUTH_HOUSING_SENDER_EMAIL"
    - name: YOUTH_HOUSING_SENDER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "airflow-env-vars"
          key: "YOUTH_HOUSING_SENDER_PASSWORD"
    - name: YOUTH_HOUSING_RECEIVER_EMAILS
      valueFrom:
        secretKeyRef:
          name: "airflow-env-vars"
          key: "YOUTH_HOUSING_RECEIVER_EMAILS"

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/Seungyeup/ScrapeAndAlert.git"
    ref: "main"
    branch: "main"
    subPath: "dags"
    wait: 60
    # credentialsSecret: "git-credentials" # public repo로 전환되어 비활성화

webserver:
  service:
    type: "NodePort"
    ports:
      - name: "airflow-ui"
        port: 8080
        targetPort: "airflow-ui"
        nodePort: 30097


postgresql:
  primary:
    persistence:
      enabled: true
      storageClass: "local-path"