executor: "KubernetesExecutor"

config:
  core:
    dags_folder: "/opt/airflow/dags/repo/dags"
    executor: "KubernetesExecutor"
    dags_are_paused_at_creation: "True"
    load_examples: "False"
  api:
    auth_backend: "airflow.api.auth.backend.basic_auth"
  logging:
    remote_logging: "False"
    logging_level: "INFO"
  kubernetes:
    delete_worker_pods: "False"
    delete_worker_pods_on_failure: "False"
    delete_worker_pods_on_success: "False"
  smtp:
    smtp_host: "{{ .Values.email.smtpHost }}"
    smtp_port: "{{ .Values.email.smtpPort }}"
    smtp_starttls: {{ .Values.email.startTls | quote }}
    smtp_ssl: {{ .Values.email.ssl | quote }}
    smtp_user: "{{ .Values.email.smtpUser }}"
    smtp_password: "{{ .Values.email.smtpPassword }}"
    smtp_mail_from: "{{ .Values.email.mailFrom }}"

images:
  airflow:
    repository: "dave126/airflow-custom"
    tag: "2.9.3-amd64"
    pullPolicy: "Always"

airflow:
  extraEnvFrom:
    - secretRef:
        name: airflow-env-vars

  extraEnv:
    # Postgres 커넥션
    - name: AIRFLOW_CONN_POSTGRES_DEFAULT
      valueFrom:
        secretKeyRef:
          name: airflow-postgresql
          key: postgres-password

    # DAG에서 참조하는 이메일 환경변수만 로드
    - name: YOUTH_HOUSING_SENDER_EMAIL
      valueFrom:
        secretKeyRef:
          name: airflow-env-vars
          key: YOUTH_HOUSING_SENDER_EMAIL
    - name: YOUTH_HOUSING_SENDER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: airflow-env-vars
          key: YOUTH_HOUSING_SENDER_PASSWORD
    - name: YOUTH_HOUSING_RECEIVER_EMAILS
      valueFrom:
        secretKeyRef:
          name: airflow-env-vars
          key: YOUTH_HOUSING_RECEIVER_EMAILS

# 실제 email.* 변수는 values.yaml 맨 아래에 정의합니다.
email:
  smtpHost: smtp.gmail.com        # SSL(465) 또는 STARTTLS(587) 중 선택
  smtpPort: "465"
  startTls: "False"               # 465 쓰면 False, 587 쓰면 True
  ssl: "True"
  smtpUser: "{{ env `YOUTH_HOUSING_SENDER_EMAIL` }}"
  smtpPassword: "{{ env `YOUTH_HOUSING_SENDER_PASSWORD` }}"
  mailFrom: "{{ env `YOUTH_HOUSING_SENDER_EMAIL` }}"

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/Seungyeup/ScrapeAndAlert.git"
    ref: "main"
    subPath: "dags"
    wait: 60

webserver:
  service:
    type: "NodePort"
    ports:
      - name: "airflow-ui"
        port: 8080
        targetPort: "airflow-ui"
        nodePort: 30097

postgresql:
  primary:
    persistence:
      enabled: true
      storageClass: "local-path"