# # .github/workflows/airflow-deploy.yml
# name: Deploy to Airflow
# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
      
#       - name: Create Kubernetes Secret
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.TAILSCALE_IP }}
#           username: ${{ secrets.K8S_USERNAME }}
#           key: ${{ secrets.K8S_SSH_KEY }}
#           script: |
#             # Secret YAML에 환경변수 주입
#             envsubst < k8s/secrets/airflow-env-vars.yaml | kubectl apply -f -
      
#       - name: Deploy Airflow
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.TAILSCALE_IP }}
#           username: ${{ secrets.K8S_USERNAME }}
#           key: ${{ secrets.K8S_SSH_KEY }}
#           script: |
#             cd /path/to/airflow/config
#             git pull
#             helm upgrade airflow apache-airflow/airflow \
#               --namespace airflow \
#               --values k8s/values.yaml

name: Deploy to Airflow
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: latest

      - name: Setup Repository on Master Node
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.K8S_HOST_IP }}
          username: ${{ secrets.K8S_USERNAME }}
          key: ${{ secrets.K8S_SSH_KEY }}
          script: |
            # 레포지토리 디렉토리가 없으면 생성
            mkdir -p /home/${{ secrets.K8S_USERNAME }}/ScrapeAndAlert
            cd /home/${{ secrets.K8S_USERNAME }}/ScrapeAndAlert
            
            # 이미 레포지토리가 있으면 pull, 없으면 clone
            if [ -d .git ]; then
              git pull
            else
              git clone https://github.com/Seungyeup/ScrapeAndAlert.git .
            fi

      - name: Create Kubernetes Secret
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.K8S_HOST_IP }}
          username: ${{ secrets.K8S_USERNAME }}
          key: ${{ secrets.K8S_SSH_KEY }}
          script: |
            cd /home/${{ secrets.K8S_USERNAME }}/ScrapeAndAlert
            # Secret YAML 생성
            cat > k8s/secrets/airflow-env-vars.yaml << EOF
            apiVersion: v1
            kind: Secret
            metadata:
              name: airflow-env-vars
              namespace: airflow
            type: Opaque
            data:
              YOUTH_HOUSING_SENDER_EMAIL: ${{ secrets.YOUTH_HOUSING_SENDER_EMAIL }}
              YOUTH_HOUSING_SENDER_PASSWORD: ${{ secrets.YOUTH_HOUSING_SENDER_PASSWORD }}
              YOUTH_HOUSING_RECEIVER_EMAILS: ${{ secrets.YOUTH_HOUSING_RECEIVER_EMAILS }}
            EOF
            
            # Secret 적용
            kubectl apply -f k8s/secrets/airflow-env-vars.yaml
      
      - name: Deploy Airflow
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.K8S_HOST_IP }}
          username: ${{ secrets.K8S_USERNAME }}
          key: ${{ secrets.K8S_SSH_KEY }}
          script: |
            cd /home/${{ secrets.K8S_USERNAME }}/ScrapeAndAlert
            git pull
            
            # Helm 저장소 추가
            helm repo add apache-airflow https://airflow.apache.org
            helm repo update
            
            # Airflow 배포
            helm upgrade airflow apache-airflow/airflow \
              --namespace airflow \
              --values k8s/values.yaml
            
            # 배포 후 상태 확인
            echo "=== Pod Status ==="
            kubectl get pods -n airflow
            
            echo "=== Webserver Logs ==="
            kubectl logs -n airflow -l component=webserver --tail=50
            
            echo "=== Scheduler Logs ==="
            kubectl logs -n airflow -l component=scheduler --tail=50
            
            echo "=== Triggerer Logs ==="
            kubectl logs -n airflow -l component=triggerer --tail=50