name: Deploy to Airflow
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: latest

      - name: Setup Repository on Master Node
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.K8S_HOST_IP }}
          username: ${{ secrets.K8S_USERNAME }}
          key: ${{ secrets.K8S_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.K8S_USERNAME }}/ScrapeAndAlert
            cd /home/${{ secrets.K8S_USERNAME }}/ScrapeAndAlert
            if [ -d .git ]; then
              git pull
            else
              git clone https://github.com/Seungyeup/ScrapeAndAlert.git .
            fi

      - name: Create Kubernetes Secret
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.K8S_HOST_IP }}
          username: ${{ secrets.K8S_USERNAME }}
          key: ${{ secrets.K8S_SSH_KEY }}
          envs: YOUTH_HOUSING_SENDER_EMAIL,YOUTH_HOUSING_SENDER_PASSWORD,YOUTH_HOUSING_RECEIVER_EMAILS
          script: |
            cd /home/${{ secrets.K8S_USERNAME }}/ScrapeAndAlert

            SENDER_EMAIL_B64=$(echo -n "$YOUTH_HOUSING_SENDER_EMAIL" | base64 | tr -d '\n')
            SENDER_PASSWORD_B64=$(echo -n "$YOUTH_HOUSING_SENDER_PASSWORD" | base64 | tr -d '\n')
            RECEIVER_EMAILS_B64=$(echo -n "$YOUTH_HOUSING_RECEIVER_EMAILS" | base64 | tr -d '\n')

            cat > k8s/secrets/airflow-env-vars.yaml <<EOF
            apiVersion: v1
            kind: Secret
            metadata:
              name: airflow-env-vars
              namespace: airflow
            type: Opaque
            data:
              YOUTH_HOUSING_SENDER_EMAIL: $SENDER_EMAIL_B64
              YOUTH_HOUSING_SENDER_PASSWORD: $SENDER_PASSWORD_B64
              YOUTH_HOUSING_RECEIVER_EMAILS: $RECEIVER_EMAILS_B64
            EOF

            kubectl apply -f k8s/secrets/airflow-env-vars.yaml

      - name: Deploy Airflow
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.K8S_HOST_IP }}
          username: ${{ secrets.K8S_USERNAME }}
          key: ${{ secrets.K8S_SSH_KEY }}
          script: |
            cd /home/${{ secrets.K8S_USERNAME }}/ScrapeAndAlert
            git pull

            helm repo add apache-airflow https://airflow.apache.org
            helm repo update

            helm upgrade airflow apache-airflow/airflow \
              --namespace airflow \
              --values k8s/values.yaml

            echo "=== Pod Status ==="
            kubectl get pods -n airflow

            echo "=== Webserver Logs ==="
            kubectl logs -n airflow -l component=webserver --tail=50

            echo "=== Scheduler Logs ==="
            kubectl logs -n airflow -l component=scheduler --tail=50

            echo "=== Triggerer Logs ==="
            kubectl logs -n airflow -l component=triggerer --tail=50
